name: practical_test
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  intl: ^0.19.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  confetti: ^0.7.0
  flutter_animate: ^4.5.0
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/
